// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Toliso.Backend.Api.Data;

#nullable disable

namespace Toliso.Backend.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Toliso.Backend.Api.Data.Entities.CreditCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Bank")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("bank");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("brand");

                    b.Property<short>("ClosingDay")
                        .HasColumnType("smallint")
                        .HasColumnName("closing_day");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("color");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<short>("DueDay")
                        .HasColumnType("smallint")
                        .HasColumnName("due_day");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("credit_cards", null, t =>
                        {
                            t.HasCheckConstraint("ck_credit_cards_brand", "brand IN ('Visa','Mastercard','Elo','AmericanExpress')");

                            t.HasCheckConstraint("ck_credit_cards_closing_day", "closing_day BETWEEN 1 AND 31");

                            t.HasCheckConstraint("ck_credit_cards_due_day", "due_day BETWEEN 1 AND 31");

                            t.HasCheckConstraint("ck_credit_cards_status", "status IN ('Active','Inactive')");
                        });
                });

            modelBuilder.Entity("Toliso.Backend.Api.Data.Entities.Entry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateOnly>("EntryDate")
                        .HasColumnType("date")
                        .HasColumnName("entry_date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("EntryDate");

                    b.HasIndex("UserId");

                    b.ToTable("entries", null, t =>
                        {
                            t.HasCheckConstraint("ck_entries_amount", "amount > 0");
                        });
                });

            modelBuilder.Entity("Toliso.Backend.Api.Data.Entities.Purchase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CardId")
                        .HasColumnType("uuid")
                        .HasColumnName("card_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("DivisionType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("division_type");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<DateOnly>("PurchaseDate")
                        .HasColumnType("date")
                        .HasColumnName("purchase_date");

                    b.Property<DateOnly?>("RecurringEndsAt")
                        .HasColumnType("date")
                        .HasColumnName("recurring_ends_at");

                    b.Property<short?>("RecurringIntervalMonths")
                        .HasColumnType("smallint")
                        .HasColumnName("recurring_interval_months");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("total_amount");

                    b.Property<short?>("TotalInstallments")
                        .HasColumnType("smallint")
                        .HasColumnName("total_installments");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("PurchaseDate");

                    b.ToTable("purchases", null, t =>
                        {
                            t.HasCheckConstraint("ck_purchases_division_type", "division_type IN ('Equal','Custom')");

                            t.HasCheckConstraint("ck_purchases_kind", "kind IN ('Single','Installment','Recurring')");

                            t.HasCheckConstraint("ck_purchases_total_amount", "total_amount > 0");

                            t.HasCheckConstraint("ck_purchases_total_installments", "kind <> 'Installment' OR (total_installments BETWEEN 2 AND 60)");
                        });
                });

            modelBuilder.Entity("Toliso.Backend.Api.Data.Entities.PurchaseOccurrence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<int>("OccurrenceNumber")
                        .HasColumnType("integer")
                        .HasColumnName("occurrence_number");

                    b.Property<Guid>("PurchaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("purchase_id");

                    b.HasKey("Id");

                    b.HasIndex("DueDate");

                    b.HasIndex("PurchaseId", "OccurrenceNumber")
                        .IsUnique();

                    b.ToTable("purchase_occurrences", null, t =>
                        {
                            t.HasCheckConstraint("ck_purchase_occurrences_number", "occurrence_number >= 1");
                        });
                });

            modelBuilder.Entity("Toliso.Backend.Api.Data.Entities.PurchaseShare", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.Property<Guid>("PurchaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("purchase_id");

                    b.Property<decimal>("ShareAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("share_amount");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("PurchaseId")
                        .IsUnique()
                        .HasDatabaseName("ix_purchase_shares_one_primary_per_purchase")
                        .HasFilter("is_primary");

                    b.HasIndex("UserId");

                    b.HasIndex("PurchaseId", "UserId")
                        .IsUnique();

                    b.ToTable("purchase_shares", null, t =>
                        {
                            t.HasCheckConstraint("ck_purchase_shares_amount", "share_amount > 0");
                        });
                });

            modelBuilder.Entity("Toliso.Backend.Api.Data.Entities.PushToken", b =>
                {
                    b.Property<string>("Token")
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DeviceName")
                        .HasColumnType("text")
                        .HasColumnName("device_name");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("platform");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Token");

                    b.HasIndex("UserId");

                    b.ToTable("push_tokens", null, t =>
                        {
                            t.HasCheckConstraint("ck_push_tokens_platform", "platform IN ('Android','Ios','Web')");
                        });
                });

            modelBuilder.Entity("Toliso.Backend.Api.Data.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("citext")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", null, t =>
                        {
                            t.HasCheckConstraint("ck_users_role", "role IN ('Admin','User')");

                            t.HasCheckConstraint("ck_users_status", "status IN ('Active','Inactive')");
                        });
                });

            modelBuilder.Entity("Toliso.Backend.Api.Data.Entities.Entry", b =>
                {
                    b.HasOne("Toliso.Backend.Api.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Toliso.Backend.Api.Data.Entities.Purchase", b =>
                {
                    b.HasOne("Toliso.Backend.Api.Data.Entities.CreditCard", null)
                        .WithMany()
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Toliso.Backend.Api.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Toliso.Backend.Api.Data.Entities.PurchaseOccurrence", b =>
                {
                    b.HasOne("Toliso.Backend.Api.Data.Entities.Purchase", "Purchase")
                        .WithMany("Occurrences")
                        .HasForeignKey("PurchaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Purchase");
                });

            modelBuilder.Entity("Toliso.Backend.Api.Data.Entities.PurchaseShare", b =>
                {
                    b.HasOne("Toliso.Backend.Api.Data.Entities.Purchase", "Purchase")
                        .WithMany("Shares")
                        .HasForeignKey("PurchaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Toliso.Backend.Api.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Purchase");
                });

            modelBuilder.Entity("Toliso.Backend.Api.Data.Entities.PushToken", b =>
                {
                    b.HasOne("Toliso.Backend.Api.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Toliso.Backend.Api.Data.Entities.Purchase", b =>
                {
                    b.Navigation("Occurrences");

                    b.Navigation("Shares");
                });
#pragma warning restore 612, 618
        }
    }
}
